name: ricardomejiastravieso
description: Software Developer - Web personal de Ricardo MejÃ­as Travieso.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: ^3.0.0
  seo_renderer: ^0.6.0
  font_awesome_flutter: ^10.1.0
  flutter_inset_box_shadow: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  provider: ^6.0.2
  url_launcher: ^6.1.5
  url_strategy: ^0.2.0
  equatable: ^2.0.5
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/app/

  fonts:
    - family: BrandIcons
      fonts:
       - asset: assets/fonts/BrandIcons.ttf
    - family: LibreBarcode
      fonts:
        - asset: assets/fonts/LibreBarcode128Text-Regular.ttf
    - family: Monoton
      fonts:
        - asset: assets/fonts/Monoton-Regular.ttf
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
          weight: 400
