name: ricardomejiastravieso
description: Software Developer - Web personal de Ricardo MejÃ­as Travieso.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^10.1.0
  flutter_inset_box_shadow: ^1.0.8
  flutter_svg: ^0.23.0+1
  url_launcher: ^6.1.5
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: LibreBarcode
      fonts:
        - asset: assets/fonts/LibreBarcode128Text-Regular.ttf
    - family: Monoton
      fonts:
        - asset: assets/fonts/Monoton-Regular.ttf
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
          weight: 400
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
