name: ricardomejiastravieso
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_svg: ^0.23.0+1
  url_launcher: ^6.1.5
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Bungee
      fonts:
        - asset: assets/fonts/BungeeShade-Regular.ttf
    - family: Fascinate
      fonts:
        - asset: assets/fonts/Fascinate-Regular.ttf
    - family: Gloria
      fonts:
        - asset: assets/fonts/GloriaHallelujah-Regular.ttf
    - family: LibreBarcode
      fonts:
        - asset: assets/fonts/LibreBarcode128Text-Regular.ttf
    - family: Monofett
      fonts:
        - asset: assets/fonts/Monofett-Regular.ttf
    - family: Monoton
      fonts:
        - asset: assets/fonts/Monoton-Regular.ttf
    - family: Rancho
      fonts:
        - asset: assets/fonts/Rancho-Regular.ttf
    - family: RubikBurned
      fonts:
        - asset: assets/fonts/RubikBurned-Regular.ttf
    - family: RubikMarkerHatch
      fonts:
        - asset: assets/fonts/RubikMarkerHatch-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
